//! Tauri command 入口,按领域拆分。

mod activity;
mod agent;
mod agents;
mod allowlist;
mod autopilot;
mod config;
mod dock;
mod error;
mod export;
mod files;
mod git;
mod hooks;
mod kms;
mod lsp;
mod media;
mod memory;
mod models;
mod remote;
mod schedule;
mod search;
pub(crate) mod sessions;
mod shell;
mod side_channel;
mod skills;
mod squad;
mod tasks;
mod update;
mod workspaces;

pub use activity::*;
pub use agent::*;
pub use agents::*;
pub use allowlist::*;
pub use autopilot::*;
pub use config::*;
pub use dock::*;
pub use error::{CommandError, CommandResult};
pub use export::*;
pub use files::*;
pub use git::*;
pub use hooks::*;
pub use kms::*;
pub use lsp::*;
pub use media::*;
pub use memory::*;
pub use models::*;
pub use remote::*;
pub use schedule::*;
pub use search::*;
pub use sessions::*;
pub use shell::*;
pub use side_channel::*;
pub use skills::*;
pub use squad::*;
pub use tasks::*;
pub use update::*;
pub use workspaces::*;
